import { ViewWrapper } from "@/src/components/wrapper/ViewWrapper";

export const metadata = {
  title: "Cart | TechMarche",
  description: "Generated by create next app",
};

export default function CartLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ViewWrapper>{children}</ViewWrapper>;
}
