import { CartPage } from "./components/CartPage";

export const metadata = {
  title: "Cart | TechMarche",
  description: "Generated by create next app",
};

export default function Cart() {
  return <CartPage />;
}
