import { ViewWrapper } from "../../components/wrapper/ViewWrapper";

export const metadata = {
  title: "Home | TechMarche",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ViewWrapper>{children}</ViewWrapper>;
}
