import "./globals.css";
import { cn } from "../lib/utils";
import { fontSans } from "../lib/fonts";
import { RootClient } from "@/src/app/components/RootClient";

export const metadata = {
  title: "TechMarche",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* // suppressHydrationWarning prevents extensions from causing a server/client mismatch */}
      <body suppressHydrationWarning={true} className={cn(fontSans.variable)}>
        <RootClient>{children}</RootClient>
      </body>
    </html>
  );
}
