import { Nav } from "@/src/app/components/nav/Nav";
import "./globals.css";
import Footer from "@/src/app/components/footer/Footer";
import { ReactQueryProvider } from "./providers/ReactQueryProvider";

export const metadata = {
  title: "TechMarche",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* // suppressHydrationWarning prevents extensions from causing a server/client mismatch */}
      <body suppressHydrationWarning={true}>
        <ReactQueryProvider>
          <Nav />
          {children}
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
