// import { ViewWrapper } from "@/src/components/wrapper/ViewWrapper";

export const metadata = {
  title: "Login | TechMarche",
  description: "Generated by create next app",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // TODO: Fix this later
  return <div className="relative pt-24">{children}</div>;
}
