import { ViewWrapper } from "../../../components/wrapper/ViewWrapper";

export const metadata = {
  title: "Product | TechMarche",
  description: "Generated by create next app",
};

export default function ProductLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <ViewWrapper>{children}</ViewWrapper>;
}
