import { ProductPage } from "./components/ProductPage";

export const metadata = {
  title: "Product | TechMarche",
  description: "Generated by create next app",
};

export default function Product({ params }: { params: { id: string } }) {
  return <ProductPage id={params.id} />;
}
