import { Metadata } from "next";
import { HomePage } from "./_components/HomePage";

export const metadata: Metadata = {
  title: "Home | TechMarche",
  description: "Generated by create next app",
};

export default function Home({
  searchParams,
}: {
  searchParams?: {
    query?: string;
  };
}) {
  const query = searchParams?.query || "";
  return <HomePage query={query} />;
}
